#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
sys.path.append(
    os.path.abspath(
        os.path.join(os.path.dirname(__file__), '..')))

from buffoon import app
app.debug = True
port = int(os.environ.get('PORT', 8015))
app.run(host='0.0.0.0', port=port)
